name: test CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main] 

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set-up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      
      - name: install dependencies
        run: npm install
      
      - name: lint code
        run: |
          npx markdownlint-cli2 "**/*.md"

      - name: run tests
        run: |
          for file in $(find . -name "*.js" -not -path "./node_modules/*"); do
            echo "Running test: $file"
            node "$file"
          done      